apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: default
spec:
  selector:
    app: flask-app
  type: ClusterIP
  ports:
    - port: 5000        # internal service port
      targetPort: 5000  # pod container port
