name: Build, Push, and Deploy to EC2 kind cluster

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build and push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/flask
          IMAGE_TAG=latest
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      # 4️⃣ Deploy to EC2 kind cluster by cloning repo
      - name: Deploy to EC2 kind cluster
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Create app folder if not exists
            mkdir -p ~/app
            cd ~/app

            # Clone repo if not exists, else pull latest
            if [ ! -d repo ]; then
              git clone https://github.com/Namra2511/Flask-app.git repo
            else
              cd repo
              git reset --hard
              git pull
            fi

            cd repo

            # Keep only k8s folder
            find . -maxdepth 1 ! -name 'k8s' ! -name '.' -exec rm -rf {} +

            # Apply Kubernetes manifests
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml

            # Wait for rollout
            kubectl rollout status deployment/flask-app
